name: "02 My Second Workflow"

on: push

jobs:
  print_job:
    name: "Printing Hello World"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v4  

    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"
