name: "03 Variables Workflow"

on: push

jobs:
  first_print_job:
    name: "Printing Hello World"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v4  

    - name: Env Variables Displaying 1st Time
      run: |
        echo "Username is ${{ vars.USERNAME }}"
        echo "Password is ${{ secrets.PASSWORD }}"

    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"