name: "03 Variables Workflow"

on: push

jobs:
  first_print_job:
    name: "Printing Hello World"
    runs-on: ubuntu-latest
    env:
      USERNAME: "Vinodh"
      PASSWORD: "mysecretpassword"

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v4  

    - name: Env Variables Displaying 1st Time
      run: |
        echo "Username is $USERNAME"
        echo "Password is $PASSWORD"

    - name: Env Variables Displaying 2nd Time
      run: |
        echo "Username is $USERNAME"
        echo "Password is $PASSWORD"

    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"

  second_print_job:
    name: "Printing Hello World"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v4  

    - name: Env Variables Displaying 1st Time
      run: |
        echo "Username is $USERNAME"
        echo "Password is $PASSWORD"

    - name: Env Variables Displaying 2nd Time
      run: |
        echo "Username is $USERNAME"
        echo "Password is $PASSWORD"

    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"