name: "03 Variables Workflow"

on: push

jobs:
  first_print_job:
    name: "first_print_job"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v4  

    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"
    
    - name: "Echo Statement"
      run: sleep 30

  second_print_job:
    name: "second_print_job"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code Base
      uses: actions/checkout@v4  

    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"
    
    - name: "Echo Statement"
      run: sleep 30      