name: "05 Job Triggers"

on: 
    issues: 
        types: 
            - opened
    pull_request: 
    repository_dispatch: 
    schedule:
    - cron: '*/5 * * * *'

jobs:
  print_job:
    name: "Printing Hello World"
    runs-on: ubuntu-latest

    steps:
    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"
