name: "06 Workflow Concurrency"

on: 
    pull_request: 
    workflow_dispatch:
    push:
    
jobs:
  print_job:
    name: "Concurrency Demo"
    runs-on: ubuntu-latest

    steps:
    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"
    
    - name: "Echo Statement"
      run: sleep 600