name: "07 Matrix Workflow"

on: push

jobs:
  print_job_1:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine, busybox]

    runs-on: ${{ matrix.os }}
    name: "Printing Hello World"
  
    steps:
      - name: "printing docker info on ${{ matrix.os }} with image ${{ matrix.images }}"
        run: docker info

      - name: sleep
        run: sleep 30  