name: "07 Matrix Workflow"

on: push

jobs:
  print_job_1:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine, busybox]
        exclude:
          - images: alpine
            os: windows-latest
          - images: busybox
            os: windows-latest
        include:
          - images: nginx
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    name: "Printing Hello World"
  
    steps:
      - name: "printing docker info on ${{ matrix.os }} with image ${{ matrix.images }}"
        run: docker info
      
      - name: checking docker ps
        run: |
          docker run ${{ matrix.images }}
          docker ps -a

      - name: sleep
        run: sleep 30  