name: "07 Matrix Workflow"

on: push

jobs:
  print_job_1:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.os }}
    name: "Printing Hello World"
  
    steps:
      - name: "Echo Statement"
        run: echo "!!! Welcome to my first workflow in Github !!!"

      - name: sleep
        run: sleep 30  