name: "07 Matrix Demo"

on: 
    pull_request: 
    workflow_dispatch:
    push:
    
jobs:
  print_job:
    name: "Matrix Demo"
    runs-on: [ubuntu-latest, windows-latest]

    steps:
    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"
    
    - name: "Echo Statement"
      run: sleep 30
