name: "10-workflow-filters"

on: 
  push:
    branches: 
      - "main"
      
jobs:
  workflow-filters:
    name: "10-workflow-filters"
    runs-on: ubuntu-latest

    steps:
    - name: "Echo Statement"
      run: echo "!!! Welcome to my first workflow in Github !!!"
    
    - name: "sleep"
      run: sleep 60
