name: "11-status-checks"

on: push

jobs:
  status-checks:
    name: "11-status-checks"
    runs-on: ubuntu-latest

    steps:
    - name: "Build Step"
      run: echo "!!! Build Successful !!!"

    - name: "Code Quality"
      id: code_quality
      run: |
        echo "!!! Code Quality !!!"
        exit 1

    - name: "Code Quality steps information"
      if: steps.code_quality.conclusion == 'failure'
      run: |
        echo "checked for failure of previous job"
        
    - name: "Packaging"
      if: failure()
      run: echo "ran on failure of previous step"      

    - name: "sleep"
      if: failure()
      run: sleep 60

    - name: "Packaging 2"
      if: cancelled()
      run: echo "ran on cancel of previous step"    

      